create TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    category_id        BIGINT REFERENCES categories(id),
    initiator_id       BIGINT REFERENCES users (id),
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    state              VARCHAR(20)                             NOT NULL,
    lat                FLOAT,
    lon                FLOAT
);

create TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT REFERENCES events(id),
    requester_id BIGINT REFERENCES users(id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)
);

create TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50)                             NOT NULL,
    pinned BOOLEAN                                 NOT NULL
);

create TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations (id),
    event_id       BIGINT NOT NULL REFERENCES events (id),
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
);

create TABLE IF NOT EXISTS comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         TEXT NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    event_id     BIGINT NOT NULL REFERENCES events (id),
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id  ON comments(user_id);