create TABLE IF NOT EXISTS endpoint_hits (
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(2000) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
create index IF NOT EXISTS idx_endpoint_hits_app_uri_timestamp ON endpoint_hits(app, uri, timestamp);